// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "BDIMLogin.pb.h"
// @@protoc_insertion_point(imports)

@implementation BdimloginRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [BdimloginRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface BDIMLoginReq ()
@property (strong) NSString* userid;
@end

@implementation BDIMLoginReq

- (BOOL) hasUserid {
  return !!hasUserid_;
}
- (void) setHasUserid:(BOOL) _value_ {
  hasUserid_ = !!_value_;
}
@synthesize userid;
- (instancetype) init {
  if ((self = [super init])) {
    self.userid = @"";
  }
  return self;
}
static BDIMLoginReq* defaultBDIMLoginReqInstance = nil;
+ (void) initialize {
  if (self == [BDIMLoginReq class]) {
    defaultBDIMLoginReqInstance = [[BDIMLoginReq alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultBDIMLoginReqInstance;
}
- (instancetype) defaultInstance {
  return defaultBDIMLoginReqInstance;
}
- (BOOL) isInitialized {
  if (!self.hasUserid) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserid) {
    [output writeString:1 value:self.userid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasUserid) {
    size_ += computeStringSize(1, self.userid);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (BDIMLoginReq*) parseFromData:(NSData*) data {
  return (BDIMLoginReq*)[[[BDIMLoginReq builder] mergeFromData:data] build];
}
+ (BDIMLoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BDIMLoginReq*)[[[BDIMLoginReq builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BDIMLoginReq*) parseFromInputStream:(NSInputStream*) input {
  return (BDIMLoginReq*)[[[BDIMLoginReq builder] mergeFromInputStream:input] build];
}
+ (BDIMLoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BDIMLoginReq*)[[[BDIMLoginReq builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BDIMLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BDIMLoginReq*)[[[BDIMLoginReq builder] mergeFromCodedInputStream:input] build];
}
+ (BDIMLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BDIMLoginReq*)[[[BDIMLoginReq builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BDIMLoginReqBuilder*) builder {
  return [[BDIMLoginReqBuilder alloc] init];
}
+ (BDIMLoginReqBuilder*) builderWithPrototype:(BDIMLoginReq*) prototype {
  return [[BDIMLoginReq builder] mergeFrom:prototype];
}
- (BDIMLoginReqBuilder*) builder {
  return [BDIMLoginReq builder];
}
- (BDIMLoginReqBuilder*) toBuilder {
  return [BDIMLoginReq builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasUserid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userid", self.userid];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasUserid) {
    [dictionary setObject: self.userid forKey: @"userid"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[BDIMLoginReq class]]) {
    return NO;
  }
  BDIMLoginReq *otherMessage = other;
  return
      self.hasUserid == otherMessage.hasUserid &&
      (!self.hasUserid || [self.userid isEqual:otherMessage.userid]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasUserid) {
    hashCode = hashCode * 31 + [self.userid hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface BDIMLoginReqBuilder()
@property (strong) BDIMLoginReq* resultBdimloginReq;
@end

@implementation BDIMLoginReqBuilder
@synthesize resultBdimloginReq;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultBdimloginReq = [[BDIMLoginReq alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultBdimloginReq;
}
- (BDIMLoginReqBuilder*) clear {
  self.resultBdimloginReq = [[BDIMLoginReq alloc] init];
  return self;
}
- (BDIMLoginReqBuilder*) clone {
  return [BDIMLoginReq builderWithPrototype:resultBdimloginReq];
}
- (BDIMLoginReq*) defaultInstance {
  return [BDIMLoginReq defaultInstance];
}
- (BDIMLoginReq*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BDIMLoginReq*) buildPartial {
  BDIMLoginReq* returnMe = resultBdimloginReq;
  self.resultBdimloginReq = nil;
  return returnMe;
}
- (BDIMLoginReqBuilder*) mergeFrom:(BDIMLoginReq*) other {
  if (other == [BDIMLoginReq defaultInstance]) {
    return self;
  }
  if (other.hasUserid) {
    [self setUserid:other.userid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BDIMLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BDIMLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setUserid:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasUserid {
  return resultBdimloginReq.hasUserid;
}
- (NSString*) userid {
  return resultBdimloginReq.userid;
}
- (BDIMLoginReqBuilder*) setUserid:(NSString*) value {
  resultBdimloginReq.hasUserid = YES;
  resultBdimloginReq.userid = value;
  return self;
}
- (BDIMLoginReqBuilder*) clearUserid {
  resultBdimloginReq.hasUserid = NO;
  resultBdimloginReq.userid = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
