// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class BDIMLoginReq;
@class BDIMLoginReqBuilder;



@interface BdimloginRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define BDIMLoginReq_userid @"userid"
@interface BDIMLoginReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserid_:1;
  NSString* userid;
}
- (BOOL) hasUserid;
@property (readonly, strong) NSString* userid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BDIMLoginReqBuilder*) builder;
+ (BDIMLoginReqBuilder*) builder;
+ (BDIMLoginReqBuilder*) builderWithPrototype:(BDIMLoginReq*) prototype;
- (BDIMLoginReqBuilder*) toBuilder;

+ (BDIMLoginReq*) parseFromData:(NSData*) data;
+ (BDIMLoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BDIMLoginReq*) parseFromInputStream:(NSInputStream*) input;
+ (BDIMLoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BDIMLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BDIMLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BDIMLoginReqBuilder : PBGeneratedMessageBuilder {
@private
  BDIMLoginReq* resultBdimloginReq;
}

- (BDIMLoginReq*) defaultInstance;

- (BDIMLoginReqBuilder*) clear;
- (BDIMLoginReqBuilder*) clone;

- (BDIMLoginReq*) build;
- (BDIMLoginReq*) buildPartial;

- (BDIMLoginReqBuilder*) mergeFrom:(BDIMLoginReq*) other;
- (BDIMLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BDIMLoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (BDIMLoginReqBuilder*) setUserid:(NSString*) value;
- (BDIMLoginReqBuilder*) clearUserid;
@end


// @@protoc_insertion_point(global_scope)
